# Render the examples using the TCG action.

name: Render Demos

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    container:
       image: ghcr.io/trustedcomputinggroup/pandoc:0.1.2
    name: Render the example text
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Render
        uses: trustedcomputinggroup/markdown@v0.1.6
        with:
          input-md: lorem.md
          output-pdf: lorem.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: lorem.pdf
          path: lorem.pdf
          
      - name: Check in latest render
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate latest PDF
          file_pattern: lorem.pdf
        if: github.event_name != 'pull_request'
